<!-- Generated by pkgdown: do not edit by hand -->
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Introduction to `vimp` • vimp</title>

<!-- favicons -->
<link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png" />
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png" />

<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<!-- Bootstrap -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script>

<!-- bootstrap-toc -->
<link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script>

<!-- Font Awesome icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous" />

<!-- clipboard.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>

<!-- headroom.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script>

<!-- pkgdown -->
<link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script>




<meta property="og:title" content="Introduction to `vimp`" />
<meta property="og:description" content="vimp" />
<meta property="og:image" content="https://bdwilliamson.github.io/vimp/logo.png" />




<!-- mathjax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script>

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->



  </head>

  <body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">vimp</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">2.1.8</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="../articles/introduction-to-vimp.html">Introduction to `vimp`</a>
    </li>
    <li>
      <a href="../articles/precomputed-regressions.html">Using precomputed regression function estimates in `vimp`</a>
    </li>
    <li>
      <a href="../articles/types-of-vims.html">Types of VIMs</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/bdwilliamson/vimp/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
      
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

      

      </header>

<script src="introduction-to-vimp_files/header-attrs-2.4/header-attrs.js"></script>
<script src="introduction-to-vimp_files/accessible-code-block-0.0.1/empty-anchor.js"></script>

<div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Introduction to <code>vimp</code></h1>
                        <h4 class="author">Brian D. Williamson</h4>
            
            <h4 class="date">2021-02-22</h4>
      
      <small class="dont-index">Source: <a href='https://github.com/bdwilliamson/vimp/blob/master/vignettes/introduction-to-vimp.Rmd'><code>vignettes/introduction-to-vimp.Rmd</code></a></small>
      <div class="hidden name"><code>introduction-to-vimp.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p><code>vimp</code> is a package that computes nonparametric estimates of variable importance and provides valid inference on the true importance. The package supports flexible estimation of variable importance based on the difference in nonparametric <span class="math inline">\(R^2\)</span>, classification accuracy, and area under the receiver operating characteristic curve (AUC). These quantities are all nonparametric generalizations of the usual measures in simple parametric models (e.g., linear models). For more details, see the accompanying manuscripts <span class="citation">Williamson, Gilbert, Carone, et al. (2020)</span>, <span class="citation">Williamson, Gilbert, Simon, et al. (2020)</span>, and <span class="citation">Williamson and Feng (2020)</span>.</p>
<p>Variable importance estimates may be computed quickly, depending on the techniques used to estimate the underlying conditional means — if these techniques are slow, then the variable importance procedure will be slow.</p>
<p>The code can handle arbitrary dimensions of features, and may be used to estimate the importance of any single feature or group of features for predicting the outcome. The package also includes functions for cross-validated importance.</p>
<p>The author and maintainer of the <code>vimp</code> package is <a href="https://bdwilliamson.github.io/">Brian Williamson</a>. The methods implemented here have also been implemented in Python under the package <a href="https://github.com/bdwilliamson/vimpy"><code>vimpy</code></a>.</p>
</div>
<div id="installation" class="section level2">
<h2>Installation</h2>
<p>A stable version of the package may be downloaded and installed from CRAN. Type the following command in your R console to install the stable version of <code>vimp</code>:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw">install.packages</span>(<span class="st">&quot;vimp&quot;</span>)</span></code></pre></div>
<p>A development version of the package may be downloaded and installed from GitHub using the <code>devtools</code> package. Type the following command in your R console to install the development version of <code>vimp</code>:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># only run if you don&#39;t have devtools</span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="co"># previously installed</span></span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="co"># install.packages(&quot;devtools&quot;)</span></span>
<span id="cb2-4"><a href="#cb2-4"></a>devtools<span class="op">::</span><span class="kw">install_github</span>(<span class="st">&quot;bdwilliamson/vimp&quot;</span>)</span></code></pre></div>
</div>
<div id="quick-start" class="section level2">
<h2>Quick Start</h2>
<p>This section should serve as a quick guide to using the <code>vimp</code> package — we will cover the main functions for estimating <span class="math inline">\(R^2\)</span>-based variable importance using a simulated data example. More details are given in the next section.</p>
<p>First, load the <code>vimp</code> package:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="kw">library</span>(<span class="st">&quot;vimp&quot;</span>)</span></code></pre></div>
<pre><code>## vimp version 2.1.8: Perform Inference on Algorithm-Agnostic Variable Importance</code></pre>
<pre><code>## Package created on 2021-02-22</code></pre>
<p>Next, create some data:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># -------------------------------------------------------------</span></span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="co"># problem setup</span></span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="co"># -------------------------------------------------------------</span></span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="co"># set up the data</span></span>
<span id="cb6-5"><a href="#cb6-5"></a><span class="kw">set.seed</span>(<span class="dv">5678910</span>)</span>
<span id="cb6-6"><a href="#cb6-6"></a>n &lt;-<span class="st"> </span><span class="dv">1000</span></span>
<span id="cb6-7"><a href="#cb6-7"></a>p &lt;-<span class="st"> </span><span class="dv">2</span></span>
<span id="cb6-8"><a href="#cb6-8"></a>s &lt;-<span class="st"> </span><span class="dv">1</span> <span class="co"># desire importance for X_1</span></span>
<span id="cb6-9"><a href="#cb6-9"></a>x &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">replicate</span>(p, <span class="kw">runif</span>(n, <span class="dv">-1</span>, <span class="dv">1</span>)))</span>
<span id="cb6-10"><a href="#cb6-10"></a>y &lt;-<span class="st"> </span>(x[,<span class="dv">1</span>])<span class="op">^</span><span class="dv">2</span><span class="op">*</span>(x[,<span class="dv">1</span>]<span class="op">+</span><span class="dv">7</span><span class="op">/</span><span class="dv">5</span>) <span class="op">+</span><span class="st"> </span>(<span class="dv">25</span><span class="op">/</span><span class="dv">9</span>)<span class="op">*</span>(x[,<span class="dv">2</span>])<span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb6-11"><a href="#cb6-11"></a><span class="co"># set up folds for hypothesis testing</span></span>
<span id="cb6-12"><a href="#cb6-12"></a>folds &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">rep</span>(<span class="kw">seq_len</span>(<span class="dv">2</span>), <span class="dt">length =</span> <span class="kw">length</span>(y)))</span></code></pre></div>
<p>This creates a matrix of covariates <code>x</code> with two columns, a vector <code>y</code> of normally-distributed outcome values, and a set of folds for a sample of <code>n = 100</code> study participants.</p>
<p>The workhorse function of <code>vimp</code>, for <span class="math inline">\(R^2\)</span>-based variable importance, is <code>vimp_rsquared</code>. There are two ways to compute variable importance: in the first method, you allow <code>vimp</code> to run regressions for you and return variable importance; in the second method (discussed in <a href="precomputed-regressions.html">“Using precomputed regression function estimates in <code>vimp</code>”</a>), you run the regressions yourself and plug these into <code>vimp</code>. I will focus on the first method here. The basic arguments are</p>
<ul>
<li>Y: the outcome (in this example, <code>y</code>)</li>
<li>X: the covariates (in this example, <code>x</code>)</li>
<li>indx: the covariate(s) of interest for evaluating importance (here, either 1 or 2)</li>
<li>run_regression: a logical value telling <code>vimp_rsquared</code> whether or not to run a regression of Y on X (<code>TRUE</code> in this example)</li>
<li>SL.library: a “library” of learners to pass to the function <code>SuperLearner</code> (since <code>run_regression = TRUE</code>)</li>
<li>V: the number of folds to use for cross-fitted variable importance</li>
</ul>
<p>This second-to-last argument, <code>SL.library</code>, determines the estimators you want to use for the conditional mean of Y given X. Estimates of variable importance rely on good estimators of the conditional mean, so we suggest using flexible estimators and model stacking to do so. One option for this is the <code>SuperLearner</code> package; load that package using</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="kw">library</span>(<span class="st">&quot;SuperLearner&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: nnls</code></pre>
<pre><code>## Super Learner</code></pre>
<pre><code>## Version: 2.0-27-9000</code></pre>
<pre><code>## Package created on 2019-08-12</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="co"># load specific algorithms</span></span>
<span id="cb12-2"><a href="#cb12-2"></a><span class="kw">library</span>(<span class="st">&quot;ranger&quot;</span>)</span></code></pre></div>
<p>The code</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>est_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> y, <span class="dt">X =</span> x, <span class="dt">indx =</span> <span class="dv">1</span>, <span class="dt">run_regression =</span> <span class="ot">TRUE</span>,</span>
<span id="cb13-2"><a href="#cb13-2"></a><span class="dt">SL.library =</span> <span class="kw">c</span>(<span class="st">&quot;SL.ranger&quot;</span>, <span class="st">&quot;SL.mean&quot;</span>), <span class="dt">V =</span> <span class="dv">2</span>, <span class="dt">env =</span> <span class="kw">environment</span>())</span></code></pre></div>
<p>uses the Super Learner to fit the required regression functions, and computes an estimate of variable importance for the importance of <span class="math inline">\(X_1\)</span>. We can visualize the estimate, standard error, and confidence interval by printing or typing the object name:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>est_<span class="dv">1</span></span></code></pre></div>
<pre><code>## Variable importance estimates:
##       Estimate  SE        95% CI                  VIMP &gt; 0 p-value     
## s = 1 0.1320347 0.0401547 [0.05333291, 0.2107364] TRUE     0.0004653858</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="kw">print</span>(est_<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Variable importance estimates:
##       Estimate  SE        95% CI                  VIMP &gt; 0 p-value     
## s = 1 0.1320347 0.0401547 [0.05333291, 0.2107364] TRUE     0.0004653858</code></pre>
<p>This output shows that we have estimated the importance of <span class="math inline">\(X_1\)</span> to be 0.132, with a 95% confidence interval of [0.053, 0.211].</p>
</div>
<div id="detailed-guide" class="section level2">
<h2>Detailed guide</h2>
<p>In this section, we provide a fuller example of estimating <span class="math inline">\(R^2\)</span>-based variable importance in the context of the South African heart disease study data <span class="citation">(Hastie, Tibshirani, and Friedman 2009)</span>.</p>
<p>Often when working with data we attempt to estimate the conditional mean of the outcome <span class="math inline">\(Y\)</span> given features <span class="math inline">\(X\)</span>, defined as <span class="math inline">\(\mu_P(x) = E_P(Y \mid X = x)\)</span>.</p>
<p>There are many tools for estimating this conditional mean. We might choose a classical parametric tool such as linear regression. We might also want to be model-agnostic and use a more nonparametric approach to estimate the conditional mean. However,</p>
<ul>
<li>This involves using some nonparametric smoothing technique, which requires: (1) choosing a technique, and (2) selecting tuning parameters</li>
<li>Naive optimal tuning balances out the bias and variance of the smoothing estimator. Is this the correct trade-off for estimating the conditional mean?</li>
</ul>
<p>Once we have a good estimate of the conditional mean, it is often of scientific interest to understand which features contribute the most to the variation in <span class="math inline">\(\mu_P\)</span>. Specifically, we might consider <span class="math display">\[\mu_{P, s}(x) = E_P(Y \mid X_{(-s)} = x_{(-s)}),\]</span> where for a vector <span class="math inline">\(v\)</span> and a set of indices <span class="math inline">\(s\)</span>, <span class="math inline">\(v_{-(s)}\)</span> denotes the elements of <span class="math inline">\(v\)</span> with index not in <span class="math inline">\(s\)</span>. By comparing <span class="math inline">\(\mu_{P, s}\)</span> to <span class="math inline">\(\mu_P\)</span> we can evaluate the importance of the <span class="math inline">\(s\)</span>th element (or group of elements).</p>
<p>Assume that our data are generated according to the mechanism <span class="math inline">\(P_0\)</span>. We define the population <span class="math inline">\(R^2\)</span> value of a given regression function <span class="math inline">\(\mu\)</span> as <span class="math inline">\(R^2(\mu, P_0) = 1 - \frac{E_{P_0}\{Y - \mu(X)\}^2}{var_{P_0}(Y)}\)</span>, where the numerator of this expression is the population mean squared error and the denominator is the population variance. We can then define a nonparametric measure of variable importance, <span class="math display">\[\psi_{0, s} = R^2(\mu_{P_0}, P_0) - R^2(\mu_{P_0,s}, P_0),\]</span> which is the proportion of the variability in the outcome explained by including <span class="math inline">\(X_j\)</span> in our chosen estimation technique.</p>
<p>This document introduces you to the basic tools in <code>vimp</code> and how to apply them to a dataset. I will explore one method for obtaining variable estimates using <code>vimp</code>: you only specify a <em>library</em> of candidate estimators for the conditional means <span class="math inline">\(\mu_{P_0}\)</span> and <span class="math inline">\(\mu_{P_0, s}\)</span>; you allow <code>vimp</code> to obtain the optimal estimates of these quantities using the <code>SuperLearner</code> <span class="citation">(van der Laan, Polley, and Hubbard 2007)</span>, and use these estimates to obtain variable importance estimates. A second method (using precomputed estimates of the regression functions) exists and is described in <a href="precomputed-regressions.html">“Using precomputed regression function estimates in <code>vimp</code>”</a>.</p>
<div id="a-look-at-the-south-african-heart-disease-study-data" class="section level3">
<h3>A look at the South African heart disease study data</h3>
<p>Throughout this document I will use the South African heart disease study data <span class="citation">(Hastie, Tibshirani, and Friedman 2009)</span>, freely available from the <a href="https://web.stanford.edu/~hastie/ElemStatLearn/datasets/SAheart.data">Elements of Statistical Learning website</a>. Information about these data is available <a href="https://web.stanford.edu/~hastie/ElemStatLearn/datasets/SAheart.info.txt">here</a>.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="co"># read in the data from the Elements website</span></span>
<span id="cb18-2"><a href="#cb18-2"></a><span class="kw">library</span>(<span class="st">&quot;RCurl&quot;</span>)</span>
<span id="cb18-3"><a href="#cb18-3"></a>heart_data &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="dt">text =</span> <span class="kw">getURL</span>(<span class="st">&quot;http://web.stanford.edu/~hastie/ElemStatLearn/datasets/SAheart.data&quot;</span>), <span class="dt">header =</span> <span class="ot">TRUE</span>, <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)</span>
<span id="cb18-4"><a href="#cb18-4"></a><span class="co"># minor data cleaning</span></span>
<span id="cb18-5"><a href="#cb18-5"></a>heart &lt;-<span class="st"> </span>heart_data[, <span class="dv">2</span><span class="op">:</span><span class="kw">dim</span>(heart_data)[<span class="dv">2</span>]]</span>
<span id="cb18-6"><a href="#cb18-6"></a>heart<span class="op">$</span>famhist &lt;-<span class="st"> </span><span class="kw">ifelse</span>(heart<span class="op">$</span>famhist <span class="op">==</span><span class="st"> &quot;Present&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb18-7"><a href="#cb18-7"></a><span class="co"># sample-splitting folds for hypothesis testing</span></span>
<span id="cb18-8"><a href="#cb18-8"></a>heart_folds &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">rep</span>(<span class="kw">seq_len</span>(<span class="dv">2</span>), <span class="dt">length =</span> <span class="kw">dim</span>(heart)[<span class="dv">1</span>]))</span></code></pre></div>
<p>In addition to the indicator of myocardial infarction <code>chd</code>, the outcome of interest, there are measurements on two groups of variables. First are behavioral features: cumulative tobacco consumption, current alcohol consumption, and type A behavior (a behavioral pattern linked to stress). Second are biological features: systolic blood pressure, low-density lipoprotein (LDL) cholesterol, adiposity (similar to body mass index), family history of heart disease, obesity, and age.</p>
<p>Since there are nine features and two groups, it is of interest to determine variable importance both for the nine individual features separately and for the two groups of features.</p>
</div>
<div id="a-first-approach-linear-regression" class="section level3">
<h3>A first approach: linear regression</h3>
<p>Suppose that I believe that a linear model truly describes the relationship between the outcome and the covariates in these data. In that case, I would be justified in only fitting a linear regression to estimate the conditional means; this means that in my importance analysis, I should also use only linear regression. Note that because I chose to fit the regression functions first and then plug them into <code>vimp</code>, I need to explicitly specify the folds used for hypothesis testing. The analysis is achieved by the following:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>X &lt;-<span class="st"> </span>heart[, <span class="op">-</span><span class="kw">dim</span>(heart)[<span class="dv">2</span>]]</span>
<span id="cb19-2"><a href="#cb19-2"></a>lm_vim_sbp &lt;-<span class="st"> </span><span class="kw">vim</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> X, <span class="dt">indx =</span> <span class="dv">1</span>, <span class="dt">run_regression =</span> <span class="ot">TRUE</span>, <span class="dt">SL.library =</span> <span class="st">&quot;SL.lm&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;r_squared&quot;</span>)</span>
<span id="cb19-3"><a href="#cb19-3"></a>lm_vim_tob &lt;-<span class="st"> </span><span class="kw">vim</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> X, <span class="dt">indx =</span> <span class="dv">2</span>, <span class="dt">run_regression =</span> <span class="ot">TRUE</span>, <span class="dt">SL.library =</span> <span class="st">&quot;SL.lm&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;r_squared&quot;</span>)</span>
<span id="cb19-4"><a href="#cb19-4"></a>lm_vim_ldl &lt;-<span class="st"> </span><span class="kw">vim</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> X, <span class="dt">indx =</span> <span class="dv">3</span>, <span class="dt">run_regression =</span> <span class="ot">TRUE</span>, <span class="dt">SL.library =</span> <span class="st">&quot;SL.lm&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;r_squared&quot;</span>)</span>
<span id="cb19-5"><a href="#cb19-5"></a>lm_vim_adi &lt;-<span class="st"> </span><span class="kw">vim</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> X, <span class="dt">indx =</span> <span class="dv">4</span>, <span class="dt">run_regression =</span> <span class="ot">TRUE</span>, <span class="dt">SL.library =</span> <span class="st">&quot;SL.lm&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;r_squared&quot;</span>)</span>
<span id="cb19-6"><a href="#cb19-6"></a>lm_vim_fam &lt;-<span class="st"> </span><span class="kw">vim</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> X, <span class="dt">indx =</span> <span class="dv">5</span>, <span class="dt">run_regression =</span> <span class="ot">TRUE</span>, <span class="dt">SL.library =</span> <span class="st">&quot;SL.lm&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;r_squared&quot;</span>)</span>
<span id="cb19-7"><a href="#cb19-7"></a>lm_vim_tpa &lt;-<span class="st"> </span><span class="kw">vim</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> X, <span class="dt">indx =</span> <span class="dv">6</span>, <span class="dt">run_regression =</span> <span class="ot">TRUE</span>, <span class="dt">SL.library =</span> <span class="st">&quot;SL.lm&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;r_squared&quot;</span>)</span>
<span id="cb19-8"><a href="#cb19-8"></a>lm_vim_obe &lt;-<span class="st"> </span><span class="kw">vim</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> X, <span class="dt">indx =</span> <span class="dv">7</span>, <span class="dt">run_regression =</span> <span class="ot">TRUE</span>, <span class="dt">SL.library =</span> <span class="st">&quot;SL.lm&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;r_squared&quot;</span>)</span>
<span id="cb19-9"><a href="#cb19-9"></a>lm_vim_alc &lt;-<span class="st"> </span><span class="kw">vim</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> X, <span class="dt">indx =</span> <span class="dv">8</span>, <span class="dt">run_regression =</span> <span class="ot">TRUE</span>, <span class="dt">SL.library =</span> <span class="st">&quot;SL.lm&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;r_squared&quot;</span>)</span>
<span id="cb19-10"><a href="#cb19-10"></a>lm_vim_age &lt;-<span class="st"> </span><span class="kw">vim</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> X, <span class="dt">indx =</span> <span class="dv">9</span>, <span class="dt">run_regression =</span> <span class="ot">TRUE</span>, <span class="dt">SL.library =</span> <span class="st">&quot;SL.lm&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;r_squared&quot;</span>)</span>
<span id="cb19-11"><a href="#cb19-11"></a></span>
<span id="cb19-12"><a href="#cb19-12"></a><span class="co"># make a table with the estimates using the merge_vim() function</span></span>
<span id="cb19-13"><a href="#cb19-13"></a><span class="kw">library</span>(<span class="st">&quot;dplyr&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a>lm_mat &lt;-<span class="st"> </span><span class="kw">merge_vim</span>(lm_vim_sbp, lm_vim_tob, lm_vim_ldl, lm_vim_adi,</span>
<span id="cb23-2"><a href="#cb23-2"></a>                lm_vim_fam, lm_vim_tpa, lm_vim_obe, lm_vim_alc, lm_vim_age)</span>
<span id="cb23-3"><a href="#cb23-3"></a><span class="co"># print out the matrix</span></span>
<span id="cb23-4"><a href="#cb23-4"></a>lm_mat</span></code></pre></div>
<pre><code>## Variable importance estimates:
##       Estimate     SE         95% CI                  VIMP &gt; 0 p-value     
## s = 6 0.2306968687 0.07754543 [0.07871062, 0.3826831]  TRUE    0.0008709805
## s = 2 0.2297583908 0.07408769 [0.08454918, 0.3749676]  TRUE    0.0014740077
## s = 1 0.1243845280 0.06401668 [0.00000000, 0.2498549]  TRUE    0.0323404939
## s = 9 0.0931209210 0.06962164 [0.00000000, 0.2295768] FALSE    0.0935529736
## s = 7 0.0845631815 0.07720069 [0.00000000, 0.2358737] FALSE    0.1308871251
## s = 4 0.0754359734 0.07307546 [0.00000000, 0.2186612] FALSE    0.1545292248
## s = 5 0.0393849670 0.06391775 [0.00000000, 0.1646615] FALSE    0.2698421118
## s = 8 0.0299019189 0.07034801 [0.00000000, 0.1677815] FALSE    0.3314648344
## s = 3 0.0003397151 0.06646206 [0.00000000, 0.1306030] FALSE    0.4979267053</code></pre>
</div>
<div id="building-a-library-of-learners" class="section level3">
<h3>Building a library of learners</h3>
<p>In general, we don’t believe that a linear model truly holds. Thinking about potential model misspecification leads us to consider other algorithms. Suppose that I prefer to use generalized additive models <span class="citation">(Hastie and Tibshirani 1990)</span> to estimate <span class="math inline">\(\mu_{P_0}\)</span> and <span class="math inline">\(\mu_{P_0, s}\)</span>, so I am planning on using the <code>gam</code> package. Suppose that you prefer to use the elastic net <span class="citation">(Zou and Hastie 2005)</span>, and are planning to use the <code>glmnet</code> package.</p>
<p>The choice of either method is somewhat subjective, and I also will have to use a technique like cross-validation to determine an optimal tuning parameter in each case. It is also possible that neither additive models nor the elastic net will do a good job estimating the true conditional means!</p>
<p>This motivates using <code>SuperLearner</code> to allow the data to determine the optimal combination of <em>base learners</em> from a <em>library</em> that I define. These base learners are a combination of different methods (e.g., generalized additive models and elastic net) and instances of the same method with different tuning parameter values (e.g., additive models with 3 and 4 degrees of freedom). The Super Learner is an example of model stacking, or model aggregation — these approaches use a data-adaptive combination of base learners to make predictions.</p>
<p>For instance, my library could include the elastic net, random forests <span class="citation">(Breiman 2001)</span>, and gradient boosted trees <span class="citation">(Friedman 2001)</span> as follows:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="co"># load the library</span></span>
<span id="cb25-2"><a href="#cb25-2"></a><span class="kw">library</span>(SuperLearner)</span>
<span id="cb25-3"><a href="#cb25-3"></a></span>
<span id="cb25-4"><a href="#cb25-4"></a><span class="co"># create a function for boosted stumps</span></span>
<span id="cb25-5"><a href="#cb25-5"></a>SL.gbm<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="cf">function</span>(..., <span class="dt">interaction.depth =</span> <span class="dv">1</span>) <span class="kw">SL.gbm</span>(..., <span class="dt">interaction.depth =</span> interaction.depth)</span>
<span id="cb25-6"><a href="#cb25-6"></a></span>
<span id="cb25-7"><a href="#cb25-7"></a><span class="co"># create GAMs with different degrees of freedom</span></span>
<span id="cb25-8"><a href="#cb25-8"></a>SL.gam<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="cf">function</span>(..., <span class="dt">deg.gam =</span> <span class="dv">3</span>) <span class="kw">SL.gam</span>(..., <span class="dt">deg.gam =</span> deg.gam)</span>
<span id="cb25-9"><a href="#cb25-9"></a>SL.gam<span class="fl">.4</span> &lt;-<span class="st"> </span><span class="cf">function</span>(..., <span class="dt">deg.gam =</span> <span class="dv">4</span>) <span class="kw">SL.gam</span>(..., <span class="dt">deg.gam =</span> deg.gam)</span>
<span id="cb25-10"><a href="#cb25-10"></a>SL.gam<span class="fl">.5</span> &lt;-<span class="st"> </span><span class="cf">function</span>(..., <span class="dt">deg.gam =</span> <span class="dv">5</span>) <span class="kw">SL.gam</span>(..., <span class="dt">deg.gam =</span> deg.gam)</span>
<span id="cb25-11"><a href="#cb25-11"></a></span>
<span id="cb25-12"><a href="#cb25-12"></a><span class="co"># add more levels of alpha for glmnet</span></span>
<span id="cb25-13"><a href="#cb25-13"></a>create.SL.glmnet &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">alpha =</span> <span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>)) {</span>
<span id="cb25-14"><a href="#cb25-14"></a>  <span class="cf">for</span> (mm <span class="cf">in</span> <span class="kw">seq</span>(<span class="kw">length</span>(alpha))) {</span>
<span id="cb25-15"><a href="#cb25-15"></a>    <span class="kw">eval</span>(<span class="kw">parse</span>(<span class="dt">file =</span> <span class="st">&quot;&quot;</span>, <span class="dt">text =</span> <span class="kw">paste</span>(<span class="st">&#39;SL.glmnet.&#39;</span>, alpha[mm], <span class="st">&#39;&lt;- function(..., alpha = &#39;</span>, alpha[mm], <span class="st">&#39;) SL.glmnet(..., alpha = alpha)&#39;</span>, <span class="dt">sep =</span> <span class="st">&#39;&#39;</span>)), <span class="dt">envir =</span> .GlobalEnv)</span>
<span id="cb25-16"><a href="#cb25-16"></a>  }</span>
<span id="cb25-17"><a href="#cb25-17"></a>  <span class="kw">invisible</span>(<span class="ot">TRUE</span>)</span>
<span id="cb25-18"><a href="#cb25-18"></a>}</span>
<span id="cb25-19"><a href="#cb25-19"></a><span class="kw">create.SL.glmnet</span>()</span>
<span id="cb25-20"><a href="#cb25-20"></a></span>
<span id="cb25-21"><a href="#cb25-21"></a><span class="co"># add tuning parameters for randomForest</span></span>
<span id="cb25-22"><a href="#cb25-22"></a>create.SL.randomForest &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">tune =</span> <span class="kw">list</span>(<span class="dt">mtry =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">7</span>), <span class="dt">nodesize =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">10</span>))) {</span>
<span id="cb25-23"><a href="#cb25-23"></a>  tuneGrid &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(tune, <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)</span>
<span id="cb25-24"><a href="#cb25-24"></a>  <span class="cf">for</span> (mm <span class="cf">in</span> <span class="kw">seq</span>(<span class="kw">nrow</span>(tuneGrid))) {</span>
<span id="cb25-25"><a href="#cb25-25"></a>    <span class="kw">eval</span>(<span class="kw">parse</span>(<span class="dt">file =</span> <span class="st">&quot;&quot;</span>, <span class="dt">text =</span> <span class="kw">paste</span>(<span class="st">&quot;SL.randomForest.&quot;</span>, mm, <span class="st">&quot;&lt;- function(..., mtry = &quot;</span>, tuneGrid[mm, <span class="dv">1</span>], <span class="st">&quot;, nodesize = &quot;</span>, tuneGrid[mm, <span class="dv">2</span>], <span class="st">&quot;) SL.randomForest(..., mtry = mtry, nodesize = nodesize)&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>)), <span class="dt">envir =</span> .GlobalEnv)</span>
<span id="cb25-26"><a href="#cb25-26"></a>  }</span>
<span id="cb25-27"><a href="#cb25-27"></a>  <span class="kw">invisible</span>(<span class="ot">TRUE</span>)</span>
<span id="cb25-28"><a href="#cb25-28"></a>}</span>
<span id="cb25-29"><a href="#cb25-29"></a><span class="kw">create.SL.randomForest</span>()</span>
<span id="cb25-30"><a href="#cb25-30"></a></span>
<span id="cb25-31"><a href="#cb25-31"></a><span class="co"># create the library</span></span>
<span id="cb25-32"><a href="#cb25-32"></a>learners &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;SL.glmnet&quot;</span>, <span class="st">&quot;SL.glmnet.0.25&quot;</span>, <span class="st">&quot;SL.glmnet.0.5&quot;</span>, <span class="st">&quot;SL.glmnet.0.75&quot;</span>,</span>
<span id="cb25-33"><a href="#cb25-33"></a>              <span class="st">&quot;SL.randomForest&quot;</span>, <span class="st">&quot;SL.randomForest.1&quot;</span>, <span class="st">&quot;SL.randomForest.2&quot;</span>, <span class="st">&quot;SL.randomForest.3&quot;</span>,</span>
<span id="cb25-34"><a href="#cb25-34"></a>              <span class="st">&quot;SL.randomForest.4&quot;</span>, <span class="st">&quot;SL.randomForest.5&quot;</span>, <span class="st">&quot;SL.randomForest.6&quot;</span>, <span class="st">&quot;SL.randomForest.7&quot;</span>,</span>
<span id="cb25-35"><a href="#cb25-35"></a>              <span class="st">&quot;SL.randomForest.8&quot;</span>, <span class="st">&quot;SL.randomForest.9&quot;</span>,</span>
<span id="cb25-36"><a href="#cb25-36"></a>              <span class="st">&quot;SL.gbm.1&quot;</span>)</span></code></pre></div>
<p>Now that I have created the library of learners, I can move on to estimating variable importance.</p>
</div>
<div id="estimating-variable-importance-for-a-single-variable" class="section level3">
<h3>Estimating variable importance for a single variable</h3>
<p>The main function for R-squared-based variable importance in the <code>vimp</code> package is the <code>vimp_rsquared()</code> function. There are five main arguments to <code>vimp_rsquared()</code>:</p>
<ul>
<li><code>Y</code>, the outcome</li>
<li><code>X</code>, the covariates</li>
<li><code>indx</code>, which determines the feature I want to estimate variable importance for</li>
<li><code>SL.library</code>, the library of candidate learners</li>
<li><code>V</code>, the number of cross-validation folds to use for computing variable importance</li>
</ul>
<p>The main arguments differ if precomputed regression function estimates are used; please see <a href="precomputed-regressions.html">“Using precomputed regression function estimates in <code>vimp</code>”</a> for further discussion of this case.</p>
<p>Suppose that the first feature that I want to estimate variable importance for is family history of heart disease, <code>fam</code>. Then supplying <code>vimp_rsquared()</code> with</p>
<ul>
<li><code>Y = heart$chd</code></li>
<li><code>X = X</code></li>
<li><code>indx = 5</code></li>
<li><code>SL.library = learners</code></li>
<li><code>V = 5</code></li>
</ul>
<p>means that:</p>
<ul>
<li>I want to use <code>SuperLearner()</code> to estimate the conditional means <span class="math inline">\(\mu_{P_0}\)</span> and <span class="math inline">\(\mu_{P_0,s}\)</span>, and my candidate library is <code>learners</code></li>
<li>I want to estimate variable importance for the fifth column of the South African heart disease study covariates, which is <code>fam</code></li>
<li>I want to use five-fold cross-fitting to estimate importance</li>
</ul>
<p>The call to <code>vimp_rsquared()</code> looks like this:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="co"># load the library</span></span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="kw">library</span>(<span class="st">&quot;vimp&quot;</span>)</span>
<span id="cb26-3"><a href="#cb26-3"></a></span>
<span id="cb26-4"><a href="#cb26-4"></a><span class="co"># now estimate variable importance</span></span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> X,</span>
<span id="cb26-6"><a href="#cb26-6"></a>    <span class="dt">indx =</span> <span class="dv">5</span>, <span class="dt">run_regression =</span> <span class="ot">TRUE</span>, <span class="dt">SL.library =</span> learners, <span class="dt">V =</span> <span class="dv">5</span>)</span></code></pre></div>
<p>While this is the preferred method for estimating variable importance, using a large library of learners may cause the function to take time to run. Usually this is okay — in general, you took a long time to collect the data, so letting an algorithm run for a few hours should not be an issue.</p>
<p>However, for the sake of illustration, I can estimate varibable importance for family history only using only using a small library, a small number of cross-validation folds in the Super Learner, and a small number of cross-fitting folds as follows (again, I suggest using a larger number of folds and a larger library in practice):</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="co"># load the library</span></span>
<span id="cb27-2"><a href="#cb27-2"></a><span class="kw">library</span>(<span class="st">&quot;vimp&quot;</span>)</span>
<span id="cb27-3"><a href="#cb27-3"></a></span>
<span id="cb27-4"><a href="#cb27-4"></a><span class="co"># small learners library</span></span>
<span id="cb27-5"><a href="#cb27-5"></a>learners<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;SL.ranger&quot;</span>)</span>
<span id="cb27-6"><a href="#cb27-6"></a><span class="co"># small number of cross-fitting folds</span></span>
<span id="cb27-7"><a href="#cb27-7"></a>V &lt;-<span class="st"> </span><span class="dv">2</span></span>
<span id="cb27-8"><a href="#cb27-8"></a><span class="co"># small number of CV folds for Super Learner</span></span>
<span id="cb27-9"><a href="#cb27-9"></a>sl_cvcontrol &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">V =</span> <span class="dv">2</span>)</span>
<span id="cb27-10"><a href="#cb27-10"></a></span>
<span id="cb27-11"><a href="#cb27-11"></a><span class="co"># now estimate variable importance</span></span>
<span id="cb27-12"><a href="#cb27-12"></a>fam_vim &lt;-<span class="st"> </span><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> <span class="kw">as.data.frame</span>(heart[, <span class="op">-</span><span class="kw">dim</span>(heart)[<span class="dv">2</span>]]), <span class="dt">indx =</span> <span class="dv">5</span>, <span class="dt">SL.library =</span> learners<span class="fl">.2</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">env =</span> <span class="kw">environment</span>(), <span class="dt">V =</span> V, <span class="dt">cvControl =</span> sl_cvcontrol)</span></code></pre></div>
<pre><code>## Warning in cv_vim(Y = Y, X = X, f1 = f1, f2 = f2, indx = indx, V = V, type =
## &quot;r_squared&quot;, : Original estimate &lt; 0; returning zero.</code></pre>
<p>This code takes approximately 5 seconds to run on a (not very fast) PC. I can display these estimates:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a>fam_vim</span></code></pre></div>
<pre><code>## Variable importance estimates:
##       Estimate SE         95% CI        VIMP &gt; 0 p-value  
## s = 5 0        0.06067205 [0, 0.118915] FALSE    0.9136594</code></pre>
<p>The object returned by <code>vimp_rsquared()</code> also contains fitted values from using <code>SuperLearner()</code>; I access these using <code>$full_fit</code> and <code>$red_fit</code>. For example,</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="kw">head</span>(fam_vim<span class="op">$</span>full_fit)</span></code></pre></div>
<pre><code>## [[1]]
##              [,1]
##   [1,] 0.58860000
##   [2,] 0.46750000
##   [3,] 0.55396667
##   [4,] 0.16586667
##   [5,] 0.53133333
##   [6,] 0.51126667
##   [7,] 0.47723333
##   [8,] 0.30333333
##   [9,] 0.17800000
##  [10,] 0.47046667
##  [11,] 0.46123333
##  [12,] 0.02520000
##  [13,] 0.08663333
##  [14,] 0.15913333
##  [15,] 0.11023333
##  [16,] 0.09736667
##  [17,] 0.16700000
##  [18,] 0.39280000
##  [19,] 0.54893333
##  [20,] 0.59936667
##  [21,] 0.06646667
##  [22,] 0.23620000
##  [23,] 0.35260000
##  [24,] 0.09186667
##  [25,] 0.58176667
##  [26,] 0.21020000
##  [27,] 0.45703333
##  [28,] 0.16130000
##  [29,] 0.44070000
##  [30,] 0.30410000
##  [31,] 0.75393333
##  [32,] 0.68286667
##  [33,] 0.33980000
##  [34,] 0.08643333
##  [35,] 0.17996667
##  [36,] 0.65190000
##  [37,] 0.54836667
##  [38,] 0.17126667
##  [39,] 0.33243333
##  [40,] 0.39550000
##  [41,] 0.65530000
##  [42,] 0.44726667
##  [43,] 0.23056667
##  [44,] 0.43996667
##  [45,] 0.25703333
##  [46,] 0.50573333
##  [47,] 0.21950000
##  [48,] 0.65590000
##  [49,] 0.33476667
##  [50,] 0.42123333
##  [51,] 0.40263333
##  [52,] 0.22720000
##  [53,] 0.07206667
##  [54,] 0.28566667
##  [55,] 0.15250000
##  [56,] 0.59216667
##  [57,] 0.04670000
##  [58,] 0.47380000
##  [59,] 0.54116667
##  [60,] 0.58276667
##  [61,] 0.53076667
##  [62,] 0.50150000
##  [63,] 0.13280000
##  [64,] 0.31263333
##  [65,] 0.25990000
##  [66,] 0.58370000
##  [67,] 0.51666667
##  [68,] 0.19746667
##  [69,] 0.42953333
##  [70,] 0.30333333
##  [71,] 0.39396667
##  [72,] 0.20323333
##  [73,] 0.42146667
##  [74,] 0.46886667
##  [75,] 0.09813333
##  [76,] 0.24993333
##  [77,] 0.04420000
##  [78,] 0.57163333
##  [79,] 0.22793333
##  [80,] 0.43110000
##  [81,] 0.34016667
##  [82,] 0.44313333
##  [83,] 0.46963333
##  [84,] 0.53403333
##  [85,] 0.46316667
##  [86,] 0.29736667
##  [87,] 0.41506667
##  [88,] 0.16056667
##  [89,] 0.14333333
##  [90,] 0.39303333
##  [91,] 0.67220000
##  [92,] 0.16536667
##  [93,] 0.32390000
##  [94,] 0.55773333
##  [95,] 0.08520000
##  [96,] 0.28603333
##  [97,] 0.08676667
##  [98,] 0.33370000
##  [99,] 0.23973333
## [100,] 0.22266667
## [101,] 0.24870000
## [102,] 0.41706667
## [103,] 0.37433333
## [104,] 0.55760000
## [105,] 0.52373333
## [106,] 0.23700000
## [107,] 0.49853333
## [108,] 0.57810000
## [109,] 0.30933333
## [110,] 0.58840000
## [111,] 0.06886667
## [112,] 0.23843333
## [113,] 0.23146667
## [114,] 0.11340000
## [115,] 0.18396667
## [116,] 0.19246667
## 
## [[2]]
##              [,1]
##   [1,] 0.20346667
##   [2,] 0.05783333
##   [3,] 0.69640000
##   [4,] 0.48350000
##   [5,] 0.45460000
##   [6,] 0.34390000
##   [7,] 0.46450000
##   [8,] 0.58070000
##   [9,] 0.16296667
##  [10,] 0.42276667
##  [11,] 0.36716667
##  [12,] 0.49880000
##  [13,] 0.21940000
##  [14,] 0.79166667
##  [15,] 0.12316667
##  [16,] 0.38653333
##  [17,] 0.17146667
##  [18,] 0.30490000
##  [19,] 0.16553333
##  [20,] 0.13443333
##  [21,] 0.29426667
##  [22,] 0.12440000
##  [23,] 0.18286667
##  [24,] 0.20953333
##  [25,] 0.20326667
##  [26,] 0.45086667
##  [27,] 0.16363333
##  [28,] 0.19426667
##  [29,] 0.12786667
##  [30,] 0.44326667
##  [31,] 0.54516667
##  [32,] 0.29043333
##  [33,] 0.26800000
##  [34,] 0.26810000
##  [35,] 0.20883333
##  [36,] 0.44626667
##  [37,] 0.52000000
##  [38,] 0.13210000
##  [39,] 0.42776667
##  [40,] 0.31133333
##  [41,] 0.19283333
##  [42,] 0.59506667
##  [43,] 0.71590000
##  [44,] 0.59876667
##  [45,] 0.11986667
##  [46,] 0.53370000
##  [47,] 0.18016667
##  [48,] 0.22516667
##  [49,] 0.56656667
##  [50,] 0.69576667
##  [51,] 0.19866667
##  [52,] 0.25393333
##  [53,] 0.50123333
##  [54,] 0.24620000
##  [55,] 0.21236667
##  [56,] 0.70506667
##  [57,] 0.53060000
##  [58,] 0.09936667
##  [59,] 0.39926667
##  [60,] 0.47340000
##  [61,] 0.33186667
##  [62,] 0.13536667
##  [63,] 0.55360000
##  [64,] 0.39953333
##  [65,] 0.13503333
##  [66,] 0.17533333
##  [67,] 0.63356667
##  [68,] 0.12983333
##  [69,] 0.13980000
##  [70,] 0.24160000
##  [71,] 0.37623333
##  [72,] 0.13806667
##  [73,] 0.07943333
##  [74,] 0.34470000
##  [75,] 0.20730000
##  [76,] 0.60220000
##  [77,] 0.59610000
##  [78,] 0.23920000
##  [79,] 0.17623333
##  [80,] 0.63330000
##  [81,] 0.41706667
##  [82,] 0.65873333
##  [83,] 0.29120000
##  [84,] 0.08093333
##  [85,] 0.43763333
##  [86,] 0.72013333
##  [87,] 0.56246667
##  [88,] 0.44190000
##  [89,] 0.18696667
##  [90,] 0.23393333
##  [91,] 0.46790000
##  [92,] 0.40660000
##  [93,] 0.44043333
##  [94,] 0.18023333
##  [95,] 0.17480000
##  [96,] 0.53920000
##  [97,] 0.28363333
##  [98,] 0.59393333
##  [99,] 0.13090000
## [100,] 0.64650000
## [101,] 0.31426667
## [102,] 0.22980000
## [103,] 0.18800000
## [104,] 0.09533333
## [105,] 0.31186667
## [106,] 0.51140000
## [107,] 0.72446667
## [108,] 0.21386667
## [109,] 0.21326667
## [110,] 0.12743333
## [111,] 0.19116667
## [112,] 0.36003333
## [113,] 0.32796667
## [114,] 0.42933333
## [115,] 0.45110000</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="kw">head</span>(fam_vim<span class="op">$</span>red_fit)</span></code></pre></div>
<pre><code>## [[1]]
##              [,1]
##   [1,] 0.28380735
##   [2,] 0.40331392
##   [3,] 0.07090634
##   [4,] 0.51798858
##   [5,] 0.58516301
##   [6,] 0.32960125
##   [7,] 0.45714019
##   [8,] 0.48346931
##   [9,] 0.43820300
##  [10,] 0.11125125
##  [11,] 0.46296540
##  [12,] 0.58721350
##  [13,] 0.50220221
##  [14,] 0.65967085
##  [15,] 0.25599469
##  [16,] 0.53141093
##  [17,] 0.24717160
##  [18,] 0.08743377
##  [19,] 0.18183548
##  [20,] 0.35443256
##  [21,] 0.64857938
##  [22,] 0.19713325
##  [23,] 0.33451562
##  [24,] 0.29497058
##  [25,] 0.04477937
##  [26,] 0.15399466
##  [27,] 0.49364856
##  [28,] 0.23225972
##  [29,] 0.47052194
##  [30,] 0.51197019
##  [31,] 0.15773714
##  [32,] 0.02637028
##  [33,] 0.67373936
##  [34,] 0.26617573
##  [35,] 0.37701313
##  [36,] 0.31973713
##  [37,] 0.02550608
##  [38,] 0.28692110
##  [39,] 0.23337586
##  [40,] 0.05714497
##  [41,] 0.51271565
##  [42,] 0.31027472
##  [43,] 0.19370349
##  [44,] 0.22463344
##  [45,] 0.36485901
##  [46,] 0.49243082
##  [47,] 0.03075477
##  [48,] 0.41284166
##  [49,] 0.45002388
##  [50,] 0.55571851
##  [51,] 0.03373975
##  [52,] 0.06308946
##  [53,] 0.36446220
##  [54,] 0.14155699
##  [55,] 0.40746811
##  [56,] 0.55429256
##  [57,] 0.08473007
##  [58,] 0.33726958
##  [59,] 0.30080094
##  [60,] 0.30875212
##  [61,] 0.13840392
##  [62,] 0.51788770
##  [63,] 0.07075155
##  [64,] 0.30815368
##  [65,] 0.45740437
##  [66,] 0.58426181
##  [67,] 0.44580638
##  [68,] 0.57179039
##  [69,] 0.33841573
##  [70,] 0.43816120
##  [71,] 0.48972476
##  [72,] 0.04544682
##  [73,] 0.15694909
##  [74,] 0.50700450
##  [75,] 0.06300933
##  [76,] 0.42285264
##  [77,] 0.23988274
##  [78,] 0.48330466
##  [79,] 0.47225684
##  [80,] 0.15637678
##  [81,] 0.33737432
##  [82,] 0.45285920
##  [83,] 0.52647765
##  [84,] 0.55918191
##  [85,] 0.54191092
##  [86,] 0.18072404
##  [87,] 0.46903920
##  [88,] 0.54208824
##  [89,] 0.28692777
##  [90,] 0.55848480
##  [91,] 0.48031639
##  [92,] 0.31990909
##  [93,] 0.62202938
##  [94,] 0.25395547
##  [95,] 0.49104686
##  [96,] 0.36715154
##  [97,] 0.62564090
##  [98,] 0.51280398
##  [99,] 0.55643238
## [100,] 0.51680172
## [101,] 0.09039983
## [102,] 0.53585794
## [103,] 0.29009759
## [104,] 0.63967067
## [105,] 0.28167404
## [106,] 0.54975427
## [107,] 0.26158594
## [108,] 0.23172248
## [109,] 0.43179719
## [110,] 0.04986515
## [111,] 0.07221626
## [112,] 0.02166060
## [113,] 0.06644694
## [114,] 0.10943394
## [115,] 0.66937865
## [116,] 0.53364045
## 
## [[2]]
##               [,1]
##   [1,] 0.643554626
##   [2,] 0.344801659
##   [3,] 0.131160181
##   [4,] 0.290687233
##   [5,] 0.011270687
##   [6,] 0.606885376
##   [7,] 0.542024128
##   [8,] 0.514418044
##   [9,] 0.378213099
##  [10,] 0.089313951
##  [11,] 0.078929408
##  [12,] 0.361403254
##  [13,] 0.147575527
##  [14,] 0.044508774
##  [15,] 0.455680589
##  [16,] 0.008446883
##  [17,] 0.275838738
##  [18,] 0.336127501
##  [19,] 0.315675141
##  [20,] 0.502014534
##  [21,] 0.261991959
##  [22,] 0.405929590
##  [23,] 0.556957050
##  [24,] 0.519100061
##  [25,] 0.147063123
##  [26,] 0.440406693
##  [27,] 0.089492127
##  [28,] 0.387172086
##  [29,] 0.594881244
##  [30,] 0.406662487
##  [31,] 0.118624718
##  [32,] 0.239283884
##  [33,] 0.627389421
##  [34,] 0.176379939
##  [35,] 0.262892791
##  [36,] 0.062090879
##  [37,] 0.031008090
##  [38,] 0.076088540
##  [39,] 0.491975773
##  [40,] 0.005219068
##  [41,] 0.598302359
##  [42,] 0.508299527
##  [43,] 0.574818334
##  [44,] 0.598671786
##  [45,] 0.196822532
##  [46,] 0.292974313
##  [47,] 0.326512131
##  [48,] 0.065675477
##  [49,] 0.160106428
##  [50,] 0.024961320
##  [51,] 0.635569879
##  [52,] 0.073355319
##  [53,] 0.377143161
##  [54,] 0.136337583
##  [55,] 0.378919781
##  [56,] 0.643531670
##  [57,] 0.635134821
##  [58,] 0.610644799
##  [59,] 0.422421041
##  [60,] 0.018657063
##  [61,] 0.542308349
##  [62,] 0.175449712
##  [63,] 0.626580606
##  [64,] 0.438718226
##  [65,] 0.414370001
##  [66,] 0.015433653
##  [67,] 0.577566584
##  [68,] 0.043054308
##  [69,] 0.078414066
##  [70,] 0.590954344
##  [71,] 0.566867224
##  [72,] 0.320160988
##  [73,] 0.170872652
##  [74,] 0.022306208
##  [75,] 0.034822017
##  [76,] 0.200717886
##  [77,] 0.347206521
##  [78,] 0.435710266
##  [79,] 0.126032222
##  [80,] 0.370027830
##  [81,] 0.078180598
##  [82,] 0.227966214
##  [83,] 0.015247692
##  [84,] 0.541366253
##  [85,] 0.521750664
##  [86,] 0.160398992
##  [87,] 0.567177950
##  [88,] 0.286913943
##  [89,] 0.478049947
##  [90,] 0.075623133
##  [91,] 0.559897256
##  [92,] 0.152850791
##  [93,] 0.432014747
##  [94,] 0.420544626
##  [95,] 0.562514117
##  [96,] 0.465270031
##  [97,] 0.625411551
##  [98,] 0.255236099
##  [99,] 0.621238120
## [100,] 0.595599046
## [101,] 0.147297657
## [102,] 0.100435888
## [103,] 0.023604357
## [104,] 0.032169862
## [105,] 0.026781933
## [106,] 0.142296748
## [107,] 0.257419619
## [108,] 0.006018821
## [109,] 0.117231268
## [110,] 0.099769404
## [111,] 0.086977207
## [112,] 0.115717120
## [113,] 0.368722489
## [114,] 0.328202510
## [115,] 0.327776303</code></pre>
<p>I can obtain estimates for the remaining individual features in the same way (again using only using a small library for illustration):</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="co"># set up the data, removing the columns for alcohol use and chd</span></span>
<span id="cb35-2"><a href="#cb35-2"></a>x &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(heart[, <span class="op">-</span><span class="kw">dim</span>(heart)[<span class="dv">2</span>]])</span>
<span id="cb35-3"><a href="#cb35-3"></a></span>
<span id="cb35-4"><a href="#cb35-4"></a><span class="co"># estimate variable importance</span></span>
<span id="cb35-5"><a href="#cb35-5"></a>tpa_vim &lt;-<span class="st"> </span><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> x, <span class="dt">indx =</span> <span class="dv">6</span>, <span class="dt">SL.library =</span> learners<span class="fl">.2</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">env =</span> <span class="kw">environment</span>(), <span class="dt">V =</span> V, <span class="dt">cvControl =</span> sl_cvcontrol)</span></code></pre></div>
<pre><code>## Warning in cv_vim(Y = Y, X = X, f1 = f1, f2 = f2, indx = indx, V = V, type =
## &quot;r_squared&quot;, : Original estimate &lt; 0; returning zero.</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a>alc_vim &lt;-<span class="st"> </span><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> x, <span class="dt">indx =</span> <span class="dv">8</span>, <span class="dt">SL.library =</span> learners<span class="fl">.2</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">env =</span> <span class="kw">environment</span>(), <span class="dt">V =</span> V, <span class="dt">cvControl =</span> sl_cvcontrol)</span></code></pre></div>
<pre><code>## Warning in cv_vim(Y = Y, X = X, f1 = f1, f2 = f2, indx = indx, V = V, type =
## &quot;r_squared&quot;, : Original estimate &lt; 0; returning zero.</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a>sbp_vim &lt;-<span class="st"> </span><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> x, <span class="dt">indx =</span> <span class="dv">1</span>, <span class="dt">SL.library =</span> learners<span class="fl">.2</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">env =</span> <span class="kw">environment</span>(), <span class="dt">V =</span> V, <span class="dt">cvControl =</span> sl_cvcontrol)</span></code></pre></div>
<pre><code>## Warning in cv_vim(Y = Y, X = X, f1 = f1, f2 = f2, indx = indx, V = V, type =
## &quot;r_squared&quot;, : Original estimate &lt; 0; returning zero.</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>tob_vim &lt;-<span class="st"> </span><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> x, <span class="dt">indx =</span> <span class="dv">2</span>, <span class="dt">SL.library =</span> learners<span class="fl">.2</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">env =</span> <span class="kw">environment</span>(), <span class="dt">V =</span> V, <span class="dt">cvControl =</span> sl_cvcontrol)</span>
<span id="cb41-2"><a href="#cb41-2"></a>ldl_vim &lt;-<span class="st"> </span><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> x, <span class="dt">indx =</span> <span class="dv">3</span>, <span class="dt">SL.library =</span> learners<span class="fl">.2</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">env =</span> <span class="kw">environment</span>(), <span class="dt">V =</span> V, <span class="dt">cvControl =</span> sl_cvcontrol)</span>
<span id="cb41-3"><a href="#cb41-3"></a>adi_vim &lt;-<span class="st"> </span><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> x, <span class="dt">indx =</span> <span class="dv">4</span>, <span class="dt">SL.library =</span> learners<span class="fl">.2</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">env =</span> <span class="kw">environment</span>(), <span class="dt">V =</span> V, <span class="dt">cvControl =</span> sl_cvcontrol)</span></code></pre></div>
<pre><code>## Warning in cv_vim(Y = Y, X = X, f1 = f1, f2 = f2, indx = indx, V = V, type =
## &quot;r_squared&quot;, : Original estimate &lt; 0; returning zero.</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a>obe_vim &lt;-<span class="st"> </span><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> x, <span class="dt">indx =</span> <span class="dv">7</span>, <span class="dt">SL.library =</span> learners<span class="fl">.2</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">env =</span> <span class="kw">environment</span>(), <span class="dt">V =</span> V, <span class="dt">cvControl =</span> sl_cvcontrol)</span>
<span id="cb43-2"><a href="#cb43-2"></a>age_vim &lt;-<span class="st"> </span><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> x, <span class="dt">indx =</span> <span class="dv">9</span>, <span class="dt">SL.library =</span> learners<span class="fl">.2</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">env =</span> <span class="kw">environment</span>(), <span class="dt">V =</span> V, <span class="dt">cvControl =</span> sl_cvcontrol)</span></code></pre></div>
<p>Now that I have estimates of each of individual feature’s variable importance, I can view them all simultaneously by plotting:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a><span class="kw">library</span>(<span class="st">&quot;dplyr&quot;</span>)</span>
<span id="cb44-2"><a href="#cb44-2"></a><span class="kw">library</span>(<span class="st">&quot;tibble&quot;</span>)</span>
<span id="cb44-3"><a href="#cb44-3"></a><span class="kw">library</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb44-4"><a href="#cb44-4"></a><span class="kw">library</span>(<span class="st">&quot;cowplot&quot;</span>)</span></code></pre></div>
<pre><code>## 
## ********************************************************</code></pre>
<pre><code>## Note: As of version 1.0.0, cowplot does not change the</code></pre>
<pre><code>##   default ggplot2 theme anymore. To recover the previous</code></pre>
<pre><code>##   behavior, execute:
##   theme_set(theme_cowplot())</code></pre>
<pre><code>## ********************************************************</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a><span class="kw">theme_set</span>(<span class="kw">theme_cowplot</span>())</span>
<span id="cb50-2"><a href="#cb50-2"></a><span class="co"># combine the objects together</span></span>
<span id="cb50-3"><a href="#cb50-3"></a>ests &lt;-<span class="st"> </span><span class="kw">merge_vim</span>(sbp_vim, tob_vim, ldl_vim, adi_vim,</span>
<span id="cb50-4"><a href="#cb50-4"></a>                fam_vim, tpa_vim, obe_vim, alc_vim, age_vim)</span>
<span id="cb50-5"><a href="#cb50-5"></a>all_vars &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Sys. blood press.&quot;</span>, <span class="st">&quot;Tobacco consump.&quot;</span>, <span class="st">&quot;LDL cholesterol&quot;</span>,</span>
<span id="cb50-6"><a href="#cb50-6"></a>              <span class="st">&quot;Adiposity&quot;</span>, <span class="st">&quot;Family history&quot;</span>, <span class="st">&quot;Type A behavior&quot;</span>, <span class="st">&quot;Obesity&quot;</span>,</span>
<span id="cb50-7"><a href="#cb50-7"></a>              <span class="st">&quot;Alcohol consump.&quot;</span>, <span class="st">&quot;Age&quot;</span>)</span>
<span id="cb50-8"><a href="#cb50-8"></a></span>
<span id="cb50-9"><a href="#cb50-9"></a>est_plot_tib &lt;-<span class="st"> </span>ests<span class="op">$</span>mat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb50-10"><a href="#cb50-10"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb50-11"><a href="#cb50-11"></a>    <span class="dt">var_fct =</span> <span class="kw">rev</span>(<span class="kw">factor</span>(s, <span class="dt">levels =</span> ests<span class="op">$</span>mat<span class="op">$</span>s,</span>
<span id="cb50-12"><a href="#cb50-12"></a>                     <span class="dt">labels =</span> all_vars[<span class="kw">as.numeric</span>(ests<span class="op">$</span>mat<span class="op">$</span>s)], </span>
<span id="cb50-13"><a href="#cb50-13"></a>                     <span class="dt">ordered =</span> <span class="ot">TRUE</span>))</span>
<span id="cb50-14"><a href="#cb50-14"></a>  )</span>
<span id="cb50-15"><a href="#cb50-15"></a></span>
<span id="cb50-16"><a href="#cb50-16"></a><span class="co"># plot</span></span>
<span id="cb50-17"><a href="#cb50-17"></a>est_plot_tib <span class="op">%&gt;%</span></span>
<span id="cb50-18"><a href="#cb50-18"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> est, <span class="dt">y =</span> var_fct)) <span class="op">+</span></span>
<span id="cb50-19"><a href="#cb50-19"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb50-20"><a href="#cb50-20"></a><span class="st">  </span><span class="kw">geom_errorbarh</span>(<span class="kw">aes</span>(<span class="dt">xmin =</span> cil, <span class="dt">xmax =</span> ciu)) <span class="op">+</span></span>
<span id="cb50-21"><a href="#cb50-21"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">&quot;Variable importance estimates: &quot;</span>, R<span class="op">^</span><span class="dv">2</span>, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>))) <span class="op">+</span></span>
<span id="cb50-22"><a href="#cb50-22"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;&quot;</span>) <span class="op">+</span></span>
<span id="cb50-23"><a href="#cb50-23"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Estimated individual feature importance&quot;</span>) <span class="op">+</span></span>
<span id="cb50-24"><a href="#cb50-24"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">subtitle =</span> <span class="st">&quot;in the South African heart disease study data&quot;</span>)</span></code></pre></div>
<p><img src="introduction-to-vimp_files/figure-html/heart-vim-1.png" width="816" /></p>
</div>
</div>
<div id="estimating-variable-importance-for-a-group-of-variables" class="section level2">
<h2>Estimating variable importance for a group of variables</h2>
<p>Now that I have estimated variable importance for each of the individual features, I can estimate variable importance for each of the groups that I mentioned above: biological and behavioral features.</p>
<p>The only difference between estimating variable importance for a group of features rather than an individual feature is that now I specify a vector for <code>s</code>; I can use any of the options listed in the previous section to compute these estimates.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1"></a><span class="co"># get the estimates</span></span>
<span id="cb51-2"><a href="#cb51-2"></a>behav_vim &lt;-<span class="st"> </span><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> x, <span class="dt">indx =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">6</span>, <span class="dv">8</span>), <span class="dt">SL.library =</span> learners<span class="fl">.2</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">env =</span> <span class="kw">environment</span>(), <span class="dt">V =</span> V, <span class="dt">cvControl =</span> sl_cvcontrol)</span></code></pre></div>
<pre><code>## Warning in cv_vim(Y = Y, X = X, f1 = f1, f2 = f2, indx = indx, V = V, type =
## &quot;r_squared&quot;, : Original estimate &lt; 0; returning zero.</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1"></a>bios_vim &lt;-<span class="st"> </span><span class="kw">vimp_rsquared</span>(<span class="dt">Y =</span> heart<span class="op">$</span>chd, <span class="dt">X =</span> x, <span class="dt">indx =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">9</span>), <span class="dt">SL.library =</span> learners<span class="fl">.2</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">env =</span> <span class="kw">environment</span>(), <span class="dt">V =</span> V, <span class="dt">cvControl =</span> sl_cvcontrol)</span>
<span id="cb53-2"><a href="#cb53-2"></a></span>
<span id="cb53-3"><a href="#cb53-3"></a><span class="co"># combine and plot</span></span>
<span id="cb53-4"><a href="#cb53-4"></a>groups &lt;-<span class="st"> </span><span class="kw">merge_vim</span>(behav_vim, bios_vim)</span>
<span id="cb53-5"><a href="#cb53-5"></a>all_grp_nms &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Behavioral features&quot;</span>, <span class="st">&quot;Biological features&quot;</span>)</span>
<span id="cb53-6"><a href="#cb53-6"></a></span>
<span id="cb53-7"><a href="#cb53-7"></a>grp_plot_tib &lt;-<span class="st"> </span>groups<span class="op">$</span>mat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb53-8"><a href="#cb53-8"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb53-9"><a href="#cb53-9"></a>    <span class="dt">grp_fct =</span> <span class="kw">factor</span>(<span class="kw">case_when</span>(</span>
<span id="cb53-10"><a href="#cb53-10"></a>      s <span class="op">==</span><span class="st"> &quot;2,6,8&quot;</span> <span class="op">~</span><span class="st"> &quot;1&quot;</span>,</span>
<span id="cb53-11"><a href="#cb53-11"></a>      s <span class="op">==</span><span class="st"> &quot;1,3,4,5,7,9&quot;</span> <span class="op">~</span><span class="st"> &quot;2&quot;</span></span>
<span id="cb53-12"><a href="#cb53-12"></a>    ), <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;1&quot;</span>, <span class="st">&quot;2&quot;</span>),  <span class="dt">labels =</span> all_grp_nms, <span class="dt">ordered =</span> <span class="ot">TRUE</span>)</span>
<span id="cb53-13"><a href="#cb53-13"></a>  )</span>
<span id="cb53-14"><a href="#cb53-14"></a>grp_plot_tib <span class="op">%&gt;%</span></span>
<span id="cb53-15"><a href="#cb53-15"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> est, <span class="dt">y =</span> grp_fct)) <span class="op">+</span></span>
<span id="cb53-16"><a href="#cb53-16"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb53-17"><a href="#cb53-17"></a><span class="st">  </span><span class="kw">geom_errorbarh</span>(<span class="kw">aes</span>(<span class="dt">xmin =</span> cil, <span class="dt">xmax =</span> ciu)) <span class="op">+</span></span>
<span id="cb53-18"><a href="#cb53-18"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">&quot;Variable importance estimates: &quot;</span>, R<span class="op">^</span><span class="dv">2</span>, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>))) <span class="op">+</span></span>
<span id="cb53-19"><a href="#cb53-19"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;&quot;</span>) <span class="op">+</span></span>
<span id="cb53-20"><a href="#cb53-20"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Estimated feature group importance&quot;</span>) <span class="op">+</span></span>
<span id="cb53-21"><a href="#cb53-21"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">subtitle =</span> <span class="st">&quot;in the South African heart disease study data&quot;</span>)</span></code></pre></div>
<p><img src="introduction-to-vimp_files/figure-html/heart-group-vim-1.png" width="816" /></p>
</div>
<div id="types-of-population-variable-importance" class="section level2">
<h2>Types of population variable importance</h2>
<p>In this document, I have focused on one particular definition of population variable importance that I call <em>conditional</em> variable importance. For a further discussion of what I call <em>marginal</em> variable importance and <em>Shapley population</em> variable importance, please see <a href="types-of-vims.html">“Types of VIMs”</a>.</p>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="unnumbered">References</h2>
<div id="refs" class="references hanging-indent">
<div id="ref-breiman2001">
<p>Breiman, L. 2001. “Random Forests” 45.</p>
</div>
<div id="ref-friedman2001">
<p>Friedman, JH. 2001. “Greedy Function Approximation: A Gradient Boosting Machine.”</p>
</div>
<div id="ref-hastie1990">
<p>Hastie, TJ, and RJ Tibshirani. 1990. <em>Generalized Additive Models</em>. Vol. 43. CRC Press.</p>
</div>
<div id="ref-hastie2009">
<p>Hastie, T, R Tibshirani, and J Friedman. 2009. <em>The Elements of Statistical Learning</em>.</p>
</div>
<div id="ref-vanderlaan2007">
<p>van der Laan, MJ, EC Polley, and AE Hubbard. 2007. “Super Learner” 6.</p>
</div>
<div id="ref-williamson2020c">
<p>Williamson, Brian D, and Jean Feng. 2020. “Efficient Nonparametric Statistical Inference on Population Feature Importance Using Shapley Values.” <a href="https://arxiv.org/abs/2006.09481">https://arxiv.org/abs/2006.09481</a>.</p>
</div>
<div id="ref-williamson2020a">
<p>Williamson, Brian D, Peter B Gilbert, Marco Carone, and Noah Simon. 2020. “Nonparametric Variable Importance Assessment Using Machine Learning Techniques.”</p>
</div>
<div id="ref-williamson2020b">
<p>Williamson, Brian D, Peter B Gilbert, Noah Simon, and Marco Carone. 2020. “A Unified Approach for Inference on Algorithm-Agnostic Variable Importance.” <a href="https://arxiv.org/abs/2004.03683">https://arxiv.org/abs/2004.03683</a>.</p>
</div>
<div id="ref-zou2005">
<p>Zou, H, and TJ Hastie. 2005. “Regularization and Variable Selection via the Elastic Net.”</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc">
      <h2 data-toc-skip>Contents</h2>
    </nav>
      </div>

</div>



      <footer>
      <div class="copyright">
  <p>Developed by Brian D. Williamson.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
   </div>

  


  </body>
</html>
